import {rankShapes,imageGlyphs} from './font-matching.js';
export function setupPlus({$,fonts,loadFont,view,openFont,request,toast,getSelectedFont}){
 let active=false,licenseKey='',indexPromise,imageCanvas,crop,drag;
 const index=()=>indexPromise||(indexPromise=fetch(chrome.runtime.getURL('font-signatures.json')).then(r=>{if(!r.ok)throw new Error('Font matching data unavailable. Reinstall Font Pirate.');return r.json();}));
 const showPlus=()=>{$('plus-dialog').showModal();};
 const state=result=>{active=!!result.active;licenseKey=result.key||'';$('plus-offer').hidden=active;$('plus-active').hidden=!active;$('license-form').hidden=active;$('plus-home').textContent=active?'Plus ✓':'Plus';};
 const allowed=async()=>{try{await request({type:'PLUS_ACCESS'});return true;}catch{showPlus();return false;}};
 const tool=(title,image=false)=>{view('plus-tools');$('plus-tool-title').textContent=title;$('image-controls').hidden=!image;$('plus-results').replaceChildren();$('matching-status').textContent='';};
 const results=(ranked,sample)=>{for(const result of ranked.slice(0,8)){const font=fonts.find(f=>f.family===result.family);if(!font)continue;const row=document.createElement('div');row.className='catalog-row';const button=document.createElement('button');button.className='catalog-font';const preview=document.createElement('span');preview.className='catalog-font-sample';preview.textContent=sample||font.family;preview.style.fontFamily=`"${font.family}"`;const label=document.createElement('span');label.className='catalog-family-name';label.textContent=font.family;button.append(preview,label);button.onclick=()=>{view('catalog');openFont(font);};row.append(button);$('plus-results').append(row);loadFont(font.family).catch(()=>{});}};
 $('plus-home').onclick=showPlus;$('close-plus').onclick=()=>$('plus-dialog').close();$('back-plus').onclick=()=>view('catalog');
 $('license-form').onsubmit=async e=>{e.preventDefault();$('activate-plus').disabled=true;$('license-status').textContent='Activating…';try{state(await request({type:'PLUS_LICENSE',action:'activate',key:$('plus-key').value}));$('license-status').textContent='Plus is ready.';}catch(e){$('license-status').textContent=e.message;}finally{$('activate-plus').disabled=false;}};
 $('copy-license').onclick=()=>navigator.clipboard.writeText(licenseKey).then(()=>toast('License key copied.')).catch(()=>{$('license-status').textContent=licenseKey;});
 $('deactivate-plus').onclick=async()=>{if(!confirm('Deactivate Plus on this installation? Your license key can be used again.'))return;try{state(await request({type:'PLUS_LICENSE',action:'deactivate'}));$('license-status').textContent='Deactivated. Your pairings are unchanged.';}catch(e){$('license-status').textContent=e.message;}};
 request({type:'PLUS_LICENSE',action:'status'}).then(state).catch(e=>{$('license-status').textContent=e.message;});
 $('similar-fonts').onclick=async()=>{if(!await allowed())return;const font=getSelectedFont();tool('Similar to '+font.family);$('matching-status').textContent='Comparing letter shapes…';try{const data=await index(),reference=data.fonts[font.family],chars='agpenRMW012';if(!reference)throw new Error('This family is not in the matching index yet.');const samples=[...chars].map(c=>reference.glyphs[data.chars.indexOf(c)]);results(rankShapes(samples,chars,data,font.family),$('detail-sample').value);$('matching-status').textContent='Closest Google Fonts by letter shape.';}catch(e){$('matching-status').textContent=e.message;}};
 $('try-page').onclick=async()=>{if(!await allowed())return;$('page-preview-family').textContent=getSelectedFont().family;$('page-preview-status').textContent='';$('page-preview-dialog').showModal();};
 $('close-page-preview').onclick=()=>$('page-preview-dialog').close();
 $('apply-page-preview').onclick=async()=>{const b=$('apply-page-preview');b.disabled=true;$('page-preview-status').textContent='Loading font…';try{const result=await request({type:'PLUS_PREVIEW',family:getSelectedFont().family,scope:$('page-preview-scope').value});$('page-preview-status').textContent=result.changed?'Preview applied. Press Esc on the page to restore.':'No text found for this selection.';}catch(e){$('page-preview-status').textContent=e.message;}finally{b.disabled=false;}};
 $('restore-page').onclick=async()=>{try{await request({type:'PLUS_PREVIEW',scope:'restore'});toast('Page fonts restored.');}catch(e){toast(e.message);}};
 $('image-match').onclick=async()=>{if(await allowed())tool('Match an image',true);};
 const canvas=$('match-canvas'),ctx=canvas.getContext('2d');
 const draw=()=>{if(!imageCanvas)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(imageCanvas,0,0,canvas.width,canvas.height);if(crop){ctx.strokeStyle='#8054d9';ctx.lineWidth=2;ctx.strokeRect(crop.x,crop.y,crop.w,crop.h);}};
 $('match-file').onchange=async()=>{const file=$('match-file').files[0];if(!file)return;imageCanvas=null;crop=null;canvas.hidden=true;$('reset-crop').hidden=true;$('plus-results').replaceChildren();try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>8*1024*1024)throw new Error('Choose a PNG, JPEG or WebP under 8 MB.');const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>25000000){bitmap.close();throw new Error('Crop the image below 25 megapixels first.');}imageCanvas=document.createElement('canvas');const scale=Math.min(1,1600/bitmap.width,1200/bitmap.height);imageCanvas.width=Math.round(bitmap.width*scale);imageCanvas.height=Math.round(bitmap.height*scale);imageCanvas.getContext('2d').drawImage(bitmap,0,0,imageCanvas.width,imageCanvas.height);bitmap.close();const displayScale=Math.min(360/imageCanvas.width,240/imageCanvas.height);canvas.width=Math.max(1,Math.round(imageCanvas.width*displayScale));canvas.height=Math.max(1,Math.round(imageCanvas.height*displayScale));canvas.hidden=false;$('reset-crop').hidden=false;crop=null;draw();$('matching-status').textContent='Drag over one line, then type its letters below.';}catch(e){$('matching-status').textContent=e.message;}};
 const point=e=>{const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(canvas.width,(e.clientX-r.left)*canvas.width/r.width)),y:Math.max(0,Math.min(canvas.height,(e.clientY-r.top)*canvas.height/r.height))};};
 canvas.onpointerdown=e=>{drag=point(e);canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;const p=point(e);crop={x:Math.min(p.x,drag.x),y:Math.min(p.y,drag.y),w:Math.abs(p.x-drag.x),h:Math.abs(p.y-drag.y)};draw();};canvas.onpointerup=()=>{drag=null;if(crop&&(crop.w<5||crop.h<5))crop=null;draw();};canvas.onpointercancel=()=>{drag=null;};$('reset-crop').onclick=()=>{crop=null;draw();};
 $('run-image-match').onclick=async()=>{if(!await allowed())return;const button=$('run-image-match');button.disabled=true;$('plus-results').replaceChildren();try{if(!imageCanvas)throw new Error('Choose an image first.');const text=$('match-text').value.trim();if(!/^[a-zA-Z0-9 ]{3,32}$/.test(text)||text.replace(/ /g,'').length<3)throw new Error('Enter 3–32 Latin letters or digits, exactly as shown.');const r=crop||{x:0,y:0,w:canvas.width,h:canvas.height},scale=imageCanvas.width/canvas.width,selected=document.createElement('canvas');selected.width=Math.max(1,Math.round(r.w*scale));selected.height=Math.max(1,Math.round(r.h*scale));selected.getContext('2d').drawImage(imageCanvas,r.x*scale,r.y*scale,r.w*scale,r.h*scale,0,0,selected.width,selected.height);$('matching-status').textContent='Comparing letter shapes…';const chars=text.replace(/ /g,''),samples=imageGlyphs(selected,chars.length),data=await index();results(rankShapes(samples,chars,data),text);$('matching-status').textContent='Closest Google Fonts, not a guaranteed identification. Compare the previews.';}catch(e){$('matching-status').textContent=e.message;}finally{button.disabled=false;}};
}
